/* Generated By:JavaCC: Do not edit this line. GenIRIConstants.java */
package com.github.blazeldp.templateIRI;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GenIRIConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int PPATH = 6;
  /** RegularExpression Id. */
  int CONCAT = 7;
  /** RegularExpression Id. */
  int REPLACE = 8;
  /** RegularExpression Id. */
  int QUERY = 9;
  /** RegularExpression Id. */
  int SPLIT = 10;
  /** RegularExpression Id. */
  int PATH = 11;
  /** RegularExpression Id. */
  int RES = 12;
  /** RegularExpression Id. */
  int RESG = 13;
  /** RegularExpression Id. */
  int RPAR = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int QUOTE = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int ECHAR = 18;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "\"ppath\"",
    "\"concat\"",
    "\"replace\"",
    "\"query\"",
    "\"split\"",
    "\"path\"",
    "\"res\"",
    "\"res.graph\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\",\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
  };

}
